# Window dimensions
GAME_WIDTH = 640 #480 #
GAME_HEIGHT = 540
OBS_YOFFSET = 540

# Chat message detection
CHAT_MSG_XOFFSET = 15
CHAT_MSG_YOFFSET = 85
CHAT_MSG_WIDTH = 370
CHAT_MSG_HEIGHT = 17

# CHAT_HEADER_XOFFSET = 220
# CHAT_HEADER_YOFFSET = 30
# CHAT_HEADER_YCHANGE = -19

# Minigame detection
MINIGAME_CHECK_XOFFSET = 235 #171 #
MINIGAME_CHECK_YOFFSET = 404
MINIGAME_CHECK_WIDTH = 5
MINIGAME_CHECK_HEIGHT = 7

CAPTCHA_XRELOFFSET = 0
CAPTCHA_YRELOFFSET = 27
CAPTCHA_WIDTH = 180
CAPTCHA_HEIGHT = 49

CAPTCHA_REFRESH_XRELOFFSET = 179
CAPTCHA_REFRESH_YRELOFFSET = 92
CAPTCHA_INPUT_XRELOFFSET = 90
CAPTCHA_INPUT_YRELOFFSET = 244
CAPTCHA_BUTTON_XRELOFFSET = 91
CAPTCHA_BUTTON_YRELOFFSET = 288

TECHNICAL_BRAKE_XRELOFFSET = 293
TECHNICAL_BRAKE_YRELOFFSET = 10

MINIGAME_XOFFSET = 249 # 185 #
MINIGAME_YOFFSET = 125
MINIGAME_WIDTH = 26
MINIGAME_HEIGHT = 290

SECOND_MESSAGE_YOFFSET = -16

# Bot states
STATE_OFF = 'off'
STATE_WAITING_FOR_TEXT = 'waiting_for_text'
STATE_WAITING_TO_RETRIEVE_FISH = 'waiting_to_retrieve_fish'
STATE_WAITING_FOR_MINIGAME = 'waiting_for_minigame'
STATE_MINIGAME = 'minigame'
STATE_BURNING_MINIGAME = 'burning_minigame'

# Time thresholds
MINIGAME_WAIT_TIME = 4.5
FISH_RETRIEVAL_WAIT_TIME = (1.75, 1.95)
STATE_RETRY_INTERVAL = (3, 4)
WAITING_FOR_TEXT_TIMEOUT = 30
MAIN_LOOP_SLEEP = 0.1
MINIGAME_SLEEP = 0.05
MINIGAME_SPACE_CLICK_THRESHOLD = (0.4, 0.5)
MINIGAME_DOUBLE_SPACE_CLICK_THRESHOLD = (0.7, 0.75)

# Template search thresholds
CHAT_MSG_THRESHOLD = 0.90
CAPTCHA_HEADER_THRESHOLD = 0.80
FISH_ICON_THRESHOLD = 0.75


# Colors
MINIGAME_CHECK_TARGET_COLOR = (100, 88, 64)  # Hex #DF9E52 in BGR

# Config file path
DEFAULT_CONFIG_PATH = "config.ini"

# Load object template
MINIGAME_FISH_TEMPLATE_PATH = "templates/minigame_fish2.png"
CHAT_MSG_TEMPLATE_PATH_1 = "templates/chat_message.png"
CHAT_MSG_TEMPLATE_PATH_2 = "templates/chat_message2.png"
CHAPTCHA_HEADER_TEMPLATE_PATH = "templates/captcha_header.png"
TECHNICAL_BRAKE_PATH = "templates/technical_brake.png"
RECIEVED_TEMPLATE_PATH = "templates/recieved.png"
LOST_TEMPLATE_PATH = "templates/lost.png"
MINIGAME_TEMPLATE_PATH = "templates/minigame.png"
UPGRADE_FISHINGROD_TEMPLATE_PATH = "templates/upgrade_fishrod.png"
CAPTCHA_ALERT_PATH = "templates/captcha_alert.wav"
UPGRADE_ALERT_PATH = "templates/exp_alert.wav"
LOOT_TABLE_PATH = "templates/loot_table"